export interface CountryData {
  name: string;
  code: string;
  currency: string;
  currencyName: string;
  flag: string;
}

export const COUNTRIES: CountryData[] = [
  { name: "Afghanistan", code: "AF", currency: "AFN", currencyName: "Afghan Afghani", flag: "🇦🇫" },
  { name: "Albania", code: "AL", currency: "ALL", currencyName: "Albanian Lek", flag: "🇦🇱" },
  { name: "Algeria", code: "DZ", currency: "DZD", currencyName: "Algerian Dinar", flag: "🇩🇿" },
  { name: "Andorra", code: "AD", currency: "EUR", currencyName: "Euro", flag: "🇦🇩" },
  { name: "Angola", code: "AO", currency: "AOA", currencyName: "Angolan Kwanza", flag: "🇦🇴" },
  { name: "Argentina", code: "AR", currency: "ARS", currencyName: "Argentine Peso", flag: "🇦🇷" },
  { name: "Armenia", code: "AM", currency: "AMD", currencyName: "Armenian Dram", flag: "🇦🇲" },
  { name: "Australia", code: "AU", currency: "AUD", currencyName: "Australian Dollar", flag: "🇦🇺" },
  { name: "Austria", code: "AT", currency: "EUR", currencyName: "Euro", flag: "🇦🇹" },
  { name: "Azerbaijan", code: "AZ", currency: "AZN", currencyName: "Azerbaijani Manat", flag: "🇦🇿" },
  { name: "Bahrain", code: "BH", currency: "BHD", currencyName: "Bahraini Dinar", flag: "🇧🇭" },
  { name: "Bangladesh", code: "BD", currency: "BDT", currencyName: "Bangladeshi Taka", flag: "🇧🇩" },
  { name: "Belarus", code: "BY", currency: "BYN", currencyName: "Belarusian Ruble", flag: "🇧🇾" },
  { name: "Belgium", code: "BE", currency: "EUR", currencyName: "Euro", flag: "🇧🇪" },
  { name: "Bhutan", code: "BT", currency: "BTN", currencyName: "Bhutanese Ngultrum", flag: "🇧🇹" },
  { name: "Bolivia", code: "BO", currency: "BOB", currencyName: "Bolivian Boliviano", flag: "🇧🇴" },
  { name: "Bosnia and Herzegovina", code: "BA", currency: "BAM", currencyName: "Bosnia-Herzegovina Convertible Mark", flag: "🇧🇦" },
  { name: "Botswana", code: "BW", currency: "BWP", currencyName: "Botswana Pula", flag: "🇧🇼" },
  { name: "Brazil", code: "BR", currency: "BRL", currencyName: "Brazilian Real", flag: "🇧🇷" },
  { name: "Bulgaria", code: "BG", currency: "BGN", currencyName: "Bulgarian Lev", flag: "🇧🇬" },
  { name: "Cambodia", code: "KH", currency: "KHR", currencyName: "Cambodian Riel", flag: "🇰🇭" },
  { name: "Cameroon", code: "CM", currency: "XAF", currencyName: "Central African CFA Franc", flag: "🇨🇲" },
  { name: "Canada", code: "CA", currency: "CAD", currencyName: "Canadian Dollar", flag: "🇨🇦" },
  { name: "Central African Republic", code: "CF", currency: "XAF", currencyName: "Central African CFA Franc", flag: "🇨🇫" },
  { name: "Chad", code: "TD", currency: "XAF", currencyName: "Central African CFA Franc", flag: "🇹🇩" },
  { name: "Chile", code: "CL", currency: "CLP", currencyName: "Chilean Peso", flag: "🇨🇱" },
  { name: "China", code: "CN", currency: "CNY", currencyName: "Chinese Yuan", flag: "🇨🇳" },
  { name: "Colombia", code: "CO", currency: "COP", currencyName: "Colombian Peso", flag: "🇨🇴" },
  { name: "Congo", code: "CG", currency: "XAF", currencyName: "Central African CFA Franc", flag: "🇨🇬" },
  { name: "Costa Rica", code: "CR", currency: "CRC", currencyName: "Costa Rican Colón", flag: "🇨🇷" },
  { name: "Croatia", code: "HR", currency: "EUR", currencyName: "Euro", flag: "🇭🇷" },
  { name: "Cuba", code: "CU", currency: "CUP", currencyName: "Cuban Peso", flag: "🇨🇺" },
  { name: "Cyprus", code: "CY", currency: "EUR", currencyName: "Euro", flag: "🇨🇾" },
  { name: "Czech Republic", code: "CZ", currency: "CZK", currencyName: "Czech Koruna", flag: "🇨🇿" },
  { name: "Denmark", code: "DK", currency: "DKK", currencyName: "Danish Krone", flag: "🇩🇰" },
  { name: "Dominican Republic", code: "DO", currency: "DOP", currencyName: "Dominican Peso", flag: "🇩🇴" },
  { name: "Ecuador", code: "EC", currency: "USD", currencyName: "United States Dollar", flag: "🇪🇨" },
  { name: "Egypt", code: "EG", currency: "EGP", currencyName: "Egyptian Pound", flag: "🇪🇬" },
  { name: "El Salvador", code: "SV", currency: "USD", currencyName: "United States Dollar", flag: "🇸🇻" },
  { name: "Estonia", code: "EE", currency: "EUR", currencyName: "Euro", flag: "🇪🇪" },
  { name: "Ethiopia", code: "ET", currency: "ETB", currencyName: "Ethiopian Birr", flag: "🇪🇹" },
  { name: "Finland", code: "FI", currency: "EUR", currencyName: "Euro", flag: "🇫🇮" },
  { name: "France", code: "FR", currency: "EUR", currencyName: "Euro", flag: "🇫🇷" },
  { name: "Georgia", code: "GE", currency: "GEL", currencyName: "Georgian Lari", flag: "🇬🇪" },
  { name: "Germany", code: "DE", currency: "EUR", currencyName: "Euro", flag: "🇩🇪" },
  { name: "Ghana", code: "GH", currency: "GHS", currencyName: "Ghanaian Cedi", flag: "🇬🇭" },
  { name: "Greece", code: "GR", currency: "EUR", currencyName: "Euro", flag: "🇬🇷" },
  { name: "Guatemala", code: "GT", currency: "GTQ", currencyName: "Guatemalan Quetzal", flag: "🇬🇹" },
  { name: "Honduras", code: "HN", currency: "HNL", currencyName: "Honduran Lempira", flag: "🇭🇳" },
  { name: "Hong Kong", code: "HK", currency: "HKD", currencyName: "Hong Kong Dollar", flag: "🇭🇰" },
  { name: "Hungary", code: "HU", currency: "HUF", currencyName: "Hungarian Forint", flag: "🇭🇺" },
  { name: "Iceland", code: "IS", currency: "ISK", currencyName: "Icelandic Króna", flag: "🇮🇸" },
  { name: "India", code: "IN", currency: "INR", currencyName: "Indian Rupee", flag: "🇮🇳" },
  { name: "Indonesia", code: "ID", currency: "IDR", currencyName: "Indonesian Rupiah", flag: "🇮🇩" },
  { name: "Iran", code: "IR", currency: "IRR", currencyName: "Iranian Rial", flag: "🇮🇷" },
  { name: "Iraq", code: "IQ", currency: "IQD", currencyName: "Iraqi Dinar", flag: "🇮🇶" },
  { name: "Ireland", code: "IE", currency: "EUR", currencyName: "Euro", flag: "🇮🇪" },
  { name: "Israel", code: "IL", currency: "ILS", currencyName: "Israeli New Shekel", flag: "🇮🇱" },
  { name: "Italy", code: "IT", currency: "EUR", currencyName: "Euro", flag: "🇮🇹" },
  { name: "Jamaica", code: "JM", currency: "JMD", currencyName: "Jamaican Dollar", flag: "🇯🇲" },
  { name: "Japan", code: "JP", currency: "JPY", currencyName: "Japanese Yen", flag: "🇯🇵" },
  { name: "Jordan", code: "JO", currency: "JOD", currencyName: "Jordanian Dinar", flag: "🇯🇴" },
  { name: "Kazakhstan", code: "KZ", currency: "KZT", currencyName: "Kazakhstani Tenge", flag: "🇰🇿" },
  { name: "Kenya", code: "KE", currency: "KES", currencyName: "Kenyan Shilling", flag: "🇰🇪" },
  { name: "Kuwait", code: "KW", currency: "KWD", currencyName: "Kuwaiti Dinar", flag: "🇰🇼" },
  { name: "Kyrgyzstan", code: "KG", currency: "KGS", currencyName: "Kyrgyzstani Som", flag: "🇰🇬" },
  { name: "Laos", code: "LA", currency: "LAK", currencyName: "Lao Kip", flag: "🇱🇦" },
  { name: "Latvia", code: "LV", currency: "EUR", currencyName: "Euro", flag: "🇱🇻" },
  { name: "Lebanon", code: "LB", currency: "LBP", currencyName: "Lebanese Pound", flag: "🇱🇧" },
  { name: "Libya", code: "LY", currency: "LYD", currencyName: "Libyan Dinar", flag: "🇱🇾" },
  { name: "Lithuania", code: "LT", currency: "EUR", currencyName: "Euro", flag: "🇱🇹" },
  { name: "Luxembourg", code: "LU", currency: "EUR", currencyName: "Euro", flag: "🇱🇺" },
  { name: "Malaysia", code: "MY", currency: "MYR", currencyName: "Malaysian Ringgit", flag: "🇲🇾" },
  { name: "Maldives", code: "MV", currency: "MVR", currencyName: "Maldivian Rufiyaa", flag: "🇲🇻" },
  { name: "Malta", code: "MT", currency: "EUR", currencyName: "Euro", flag: "🇲🇹" },
  { name: "Mexico", code: "MX", currency: "MXN", currencyName: "Mexican Peso", flag: "🇲🇽" },
  { name: "Monaco", code: "MC", currency: "EUR", currencyName: "Euro", flag: "🇲🇨" },
  { name: "Mongolia", code: "MN", currency: "MNT", currencyName: "Mongolian Tögrög", flag: "🇲🇳" },
  { name: "Montenegro", code: "ME", currency: "EUR", currencyName: "Euro", flag: "🇲🇪" },
  { name: "Morocco", code: "MA", currency: "MAD", currencyName: "Moroccan Dirham", flag: "🇲🇦" },
  { name: "Myanmar", code: "MM", currency: "MMK", currencyName: "Burmese Kyat", flag: "🇲🇲" },
  { name: "Nepal", code: "NP", currency: "NPR", currencyName: "Nepalese Rupee", flag: "🇳🇵" },
  { name: "Netherlands", code: "NL", currency: "EUR", currencyName: "Euro", flag: "🇳🇱" },
  { name: "New Zealand", code: "NZ", currency: "NZD", currencyName: "New Zealand Dollar", flag: "🇳🇿" },
  { name: "Nigeria", code: "NG", currency: "NGN", currencyName: "Nigerian Naira", flag: "🇳🇬" },
  { name: "North Korea", code: "KP", currency: "KPW", currencyName: "North Korean Won", flag: "🇰🇵" },
  { name: "Norway", code: "NO", currency: "NOK", currencyName: "Norwegian Krone", flag: "🇳🇴" },
  { name: "Oman", code: "OM", currency: "OMR", currencyName: "Omani Rial", flag: "🇴🇲" },
  { name: "Pakistan", code: "PK", currency: "PKR", currencyName: "Pakistani Rupee", flag: "🇵🇰" },
  { name: "Panama", code: "PA", currency: "PAB", currencyName: "Panamanian Balboa", flag: "🇵🇦" },
  { name: "Paraguay", code: "PY", currency: "PYG", currencyName: "Paraguayan Guaraní", flag: "🇵🇾" },
  { name: "Peru", code: "PE", currency: "PEN", currencyName: "Peruvian Sol", flag: "🇵🇪" },
  { name: "Philippines", code: "PH", currency: "PHP", currencyName: "Philippine Peso", flag: "🇵🇭" },
  { name: "Poland", code: "PL", currency: "PLN", currencyName: "Polish Złoty", flag: "🇵🇱" },
  { name: "Portugal", code: "PT", currency: "EUR", currencyName: "Euro", flag: "🇵🇹" },
  { name: "Qatar", code: "QA", currency: "QAR", currencyName: "Qatari Riyal", flag: "🇶🇦" },
  { name: "Romania", code: "RO", currency: "RON", currencyName: "Romanian Leu", flag: "🇷🇴" },
  { name: "Russia", code: "RU", currency: "RUB", currencyName: "Russian Ruble", flag: "🇷🇺" },
  { name: "Saudi Arabia", code: "SA", currency: "SAR", currencyName: "Saudi Riyal", flag: "🇸🇦" },
  { name: "Serbia", code: "RS", currency: "RSD", currencyName: "Serbian Dinar", flag: "🇷🇸" },
  { name: "Singapore", code: "SG", currency: "SGD", currencyName: "Singapore Dollar", flag: "🇸🇬" },
  { name: "Slovakia", code: "SK", currency: "EUR", currencyName: "Euro", flag: "🇸🇰" },
  { name: "Slovenia", code: "SI", currency: "EUR", currencyName: "Euro", flag: "🇸🇮" },
  { name: "South Africa", code: "ZA", currency: "ZAR", currencyName: "South African Rand", flag: "🇿🇦" },
  { name: "South Korea", code: "KR", currency: "KRW", currencyName: "South Korean Won", flag: "🇰🇷" },
  { name: "Spain", code: "ES", currency: "EUR", currencyName: "Euro", flag: "🇪🇸" },
  { name: "Sri Lanka", code: "LK", currency: "LKR", currencyName: "Sri Lankan Rupee", flag: "🇱🇰" },
  { name: "Sweden", code: "SE", currency: "SEK", currencyName: "Swedish Krona", flag: "🇸🇪" },
  { name: "Switzerland", code: "CH", currency: "CHF", currencyName: "Swiss Franc", flag: "🇨🇭" },
  { name: "Syria", code: "SY", currency: "SYP", currencyName: "Syrian Pound", flag: "🇸🇾" },
  { name: "Taiwan", code: "TW", currency: "TWD", currencyName: "New Taiwan Dollar", flag: "🇹🇼" },
  { name: "Tajikistan", code: "TJ", currency: "TJS", currencyName: "Tajikistani Somoni", flag: "🇹🇯" },
  { name: "Thailand", code: "TH", currency: "THB", currencyName: "Thai Baht", flag: "🇹🇭" },
  { name: "Turkey", code: "TR", currency: "TRY", currencyName: "Turkish Lira", flag: "🇹🇷" },
  { name: "Turkmenistan", code: "TM", currency: "TMT", currencyName: "Turkmenistan Manat", flag: "🇹🇲" },
  { name: "Ukraine", code: "UA", currency: "UAH", currencyName: "Ukrainian Hryvnia", flag: "🇺🇦" },
  { name: "United Arab Emirates", code: "AE", currency: "AED", currencyName: "United Arab Emirates Dirham", flag: "🇦🇪" },
  { name: "United Kingdom", code: "GB", currency: "GBP", currencyName: "British Pound", flag: "🇬🇧" },
  { name: "United States", code: "US", currency: "USD", currencyName: "United States Dollar", flag: "🇺🇸" },
  { name: "Uruguay", code: "UY", currency: "UYU", currencyName: "Uruguayan Peso", flag: "🇺🇾" },
  { name: "Uzbekistan", code: "UZ", currency: "UZS", currencyName: "Uzbekistani So'm", flag: "🇺🇿" },
  { name: "Venezuela", code: "VE", currency: "VES", currencyName: "Venezuelan Bolívar Soberano", flag: "🇻🇪" },
  { name: "Vietnam", code: "VN", currency: "VND", currencyName: "Vietnamese Đồng", flag: "🇻🇳" },
  { name: "Yemen", code: "YE", currency: "YER", currencyName: "Yemeni Rial", flag: "🇾🇪" },
  { name: "Zimbabwe", code: "ZW", currency: "ZWL", currencyName: "Zimbabwean Dollar", flag: "🇿🇼" }
];
